// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _jedi_dnn2_float_float_dense2_config_s_HH_
#define _jedi_dnn2_float_float_dense2_config_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dnn2_float_float_dense2_config_s.h"
#include "jedi_dnn2_float_float_dense2_config_s_cache2.h"
#include "jedi_dnn1_float_float_dense1_config_s_E_col.h"

namespace ap_rtl {

struct jedi_dnn2_float_float_dense2_config_s : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<12> > C_address0;
    sc_out< sc_logic > C_ce0;
    sc_in< sc_lv<32> > C_q0;
    sc_out< sc_lv<11> > O_address0;
    sc_out< sc_logic > O_ce0;
    sc_out< sc_logic > O_we0;
    sc_out< sc_lv<32> > O_d0;


    // Module declarations
    jedi_dnn2_float_float_dense2_config_s(sc_module_name name);
    SC_HAS_PROCESS(jedi_dnn2_float_float_dense2_config_s);

    ~jedi_dnn2_float_float_dense2_config_s();

    sc_trace_file* mVcdFile;

    jedi_dnn2_float_float_dense2_config_s_cache2* cache2_U;
    jedi_dnn1_float_float_dense1_config_s_E_col* O_col_U;
    dnn2_float_float_dense2_config_s* grp_dnn2_float_float_dense2_config_s_fu_166;
    sc_signal< sc_lv<7> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > cols_fu_184_p2;
    sc_signal< sc_lv<8> > cols_reg_266;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<12> > zext_ln361_fu_190_p1;
    sc_signal< sc_lv<12> > zext_ln361_reg_271;
    sc_signal< sc_lv<1> > icmp_ln360_fu_178_p2;
    sc_signal< sc_lv<11> > zext_ln361_1_fu_194_p1;
    sc_signal< sc_lv<11> > zext_ln361_1_reg_276;
    sc_signal< sc_lv<5> > rows_fu_204_p2;
    sc_signal< sc_lv<5> > rows_reg_284;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<12> > add_ln362_1_fu_210_p2;
    sc_signal< sc_lv<12> > add_ln362_1_reg_289;
    sc_signal< sc_lv<1> > icmp_ln361_fu_198_p2;
    sc_signal< sc_lv<4> > rows_1_fu_237_p2;
    sc_signal< sc_lv<4> > rows_1_reg_302;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<11> > add_ln370_1_fu_248_p2;
    sc_signal< sc_lv<11> > add_ln370_1_reg_307;
    sc_signal< sc_lv<1> > icmp_ln369_fu_231_p2;
    sc_signal< sc_lv<11> > add_ln370_fu_254_p2;
    sc_signal< sc_lv<11> > add_ln370_reg_312;
    sc_signal< sc_lv<5> > cache2_address0;
    sc_signal< sc_logic > cache2_ce0;
    sc_signal< sc_logic > cache2_we0;
    sc_signal< sc_lv<32> > cache2_q0;
    sc_signal< sc_logic > cache2_ce1;
    sc_signal< sc_lv<32> > cache2_q1;
    sc_signal< sc_lv<4> > O_col_address0;
    sc_signal< sc_logic > O_col_ce0;
    sc_signal< sc_logic > O_col_we0;
    sc_signal< sc_lv<32> > O_col_q0;
    sc_signal< sc_logic > O_col_ce1;
    sc_signal< sc_logic > O_col_we1;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_ap_start;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_ap_done;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_ap_idle;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_ap_ready;
    sc_signal< sc_lv<5> > grp_dnn2_float_float_dense2_config_s_fu_166_input_r_address0;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_input_r_ce0;
    sc_signal< sc_lv<5> > grp_dnn2_float_float_dense2_config_s_fu_166_input_r_address1;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_input_r_ce1;
    sc_signal< sc_lv<4> > grp_dnn2_float_float_dense2_config_s_fu_166_res_address0;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_res_ce0;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_res_we0;
    sc_signal< sc_lv<32> > grp_dnn2_float_float_dense2_config_s_fu_166_res_d0;
    sc_signal< sc_lv<4> > grp_dnn2_float_float_dense2_config_s_fu_166_res_address1;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_res_ce1;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_res_we1;
    sc_signal< sc_lv<32> > grp_dnn2_float_float_dense2_config_s_fu_166_res_d1;
    sc_signal< sc_lv<8> > cols_0_reg_110;
    sc_signal< sc_lv<5> > rows_0_reg_121;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<12> > phi_mul_reg_133;
    sc_signal< sc_lv<4> > rows1_0_reg_144;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<11> > phi_mul1_reg_155;
    sc_signal< sc_logic > grp_dnn2_float_float_dense2_config_s_fu_166_ap_start_reg;
    sc_signal< sc_lv<64> > zext_ln362_1_fu_221_p1;
    sc_signal< sc_lv<64> > zext_ln362_fu_226_p1;
    sc_signal< sc_lv<64> > zext_ln370_fu_243_p1;
    sc_signal< sc_lv<64> > zext_ln370_1_fu_259_p1;
    sc_signal< sc_lv<12> > add_ln362_fu_216_p2;
    sc_signal< sc_lv<7> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<7> ap_ST_fsm_state1;
    static const sc_lv<7> ap_ST_fsm_state2;
    static const sc_lv<7> ap_ST_fsm_state3;
    static const sc_lv<7> ap_ST_fsm_state4;
    static const sc_lv<7> ap_ST_fsm_state5;
    static const sc_lv<7> ap_ST_fsm_state6;
    static const sc_lv<7> ap_ST_fsm_state7;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<8> ap_const_lv8_96;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<5> ap_const_lv5_1A;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<12> ap_const_lv12_96;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<11> ap_const_lv11_96;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_C_address0();
    void thread_C_ce0();
    void thread_O_address0();
    void thread_O_ce0();
    void thread_O_col_address0();
    void thread_O_col_ce0();
    void thread_O_col_ce1();
    void thread_O_col_we0();
    void thread_O_col_we1();
    void thread_O_d0();
    void thread_O_we0();
    void thread_add_ln362_1_fu_210_p2();
    void thread_add_ln362_fu_216_p2();
    void thread_add_ln370_1_fu_248_p2();
    void thread_add_ln370_fu_254_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_cache2_address0();
    void thread_cache2_ce0();
    void thread_cache2_ce1();
    void thread_cache2_we0();
    void thread_cols_fu_184_p2();
    void thread_grp_dnn2_float_float_dense2_config_s_fu_166_ap_start();
    void thread_icmp_ln360_fu_178_p2();
    void thread_icmp_ln361_fu_198_p2();
    void thread_icmp_ln369_fu_231_p2();
    void thread_rows_1_fu_237_p2();
    void thread_rows_fu_204_p2();
    void thread_zext_ln361_1_fu_194_p1();
    void thread_zext_ln361_fu_190_p1();
    void thread_zext_ln362_1_fu_221_p1();
    void thread_zext_ln362_fu_226_p1();
    void thread_zext_ln370_1_fu_259_p1();
    void thread_zext_ln370_fu_243_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
