// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "jedi_dnn3_float_float_dense3_config_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic jedi_dnn3_float_float_dense3_config_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic jedi_dnn3_float_float_dense3_config_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state1 = "1";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state2 = "10";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state3 = "100";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state4 = "1000";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state5 = "10000";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state6 = "100000";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> jedi_dnn3_float_float_dense3_config_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> jedi_dnn3_float_float_dense3_config_s::ap_const_lv32_1 = "1";
const sc_lv<32> jedi_dnn3_float_float_dense3_config_s::ap_const_lv32_2 = "10";
const sc_lv<1> jedi_dnn3_float_float_dense3_config_s::ap_const_lv1_0 = "0";
const sc_lv<32> jedi_dnn3_float_float_dense3_config_s::ap_const_lv32_3 = "11";
const sc_lv<32> jedi_dnn3_float_float_dense3_config_s::ap_const_lv32_4 = "100";
const sc_lv<32> jedi_dnn3_float_float_dense3_config_s::ap_const_lv32_8 = "1000";
const sc_lv<4> jedi_dnn3_float_float_dense3_config_s::ap_const_lv4_0 = "0000";
const sc_lv<1> jedi_dnn3_float_float_dense3_config_s::ap_const_lv1_1 = "1";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_const_lv11_0 = "00000000000";
const sc_lv<32> jedi_dnn3_float_float_dense3_config_s::ap_const_lv32_9 = "1001";
const sc_lv<8> jedi_dnn3_float_float_dense3_config_s::ap_const_lv8_0 = "00000000";
const sc_lv<32> jedi_dnn3_float_float_dense3_config_s::ap_const_lv32_A = "1010";
const sc_lv<32> jedi_dnn3_float_float_dense3_config_s::ap_const_lv32_5 = "101";
const sc_lv<4> jedi_dnn3_float_float_dense3_config_s::ap_const_lv4_A = "1010";
const sc_lv<4> jedi_dnn3_float_float_dense3_config_s::ap_const_lv4_1 = "1";
const sc_lv<11> jedi_dnn3_float_float_dense3_config_s::ap_const_lv11_96 = "10010110";
const sc_lv<8> jedi_dnn3_float_float_dense3_config_s::ap_const_lv8_96 = "10010110";
const sc_lv<8> jedi_dnn3_float_float_dense3_config_s::ap_const_lv8_1 = "1";
const bool jedi_dnn3_float_float_dense3_config_s::ap_const_boolean_1 = true;

jedi_dnn3_float_float_dense3_config_s::jedi_dnn3_float_float_dense3_config_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    O_sum_U = new jedi_dnn3_float_float_dense3_config_s_O_sum("O_sum_U");
    O_sum_U->clk(ap_clk);
    O_sum_U->reset(ap_rst);
    O_sum_U->address0(O_sum_address0);
    O_sum_U->ce0(O_sum_ce0);
    O_sum_U->we0(O_sum_we0);
    O_sum_U->d0(O_sum_d0);
    O_sum_U->q0(O_sum_q0);
    O_sum_U->address1(grp_dnn3_float_float_dense3_config_s_fu_121_input_r_address1);
    O_sum_U->ce1(O_sum_ce1);
    O_sum_U->q1(O_sum_q1);
    grp_dnn3_float_float_dense3_config_s_fu_121 = new dnn3_float_float_dense3_config_s("grp_dnn3_float_float_dense3_config_s_fu_121");
    grp_dnn3_float_float_dense3_config_s_fu_121->ap_clk(ap_clk);
    grp_dnn3_float_float_dense3_config_s_fu_121->ap_rst(ap_rst);
    grp_dnn3_float_float_dense3_config_s_fu_121->ap_start(grp_dnn3_float_float_dense3_config_s_fu_121_ap_start);
    grp_dnn3_float_float_dense3_config_s_fu_121->ap_done(grp_dnn3_float_float_dense3_config_s_fu_121_ap_done);
    grp_dnn3_float_float_dense3_config_s_fu_121->ap_idle(grp_dnn3_float_float_dense3_config_s_fu_121_ap_idle);
    grp_dnn3_float_float_dense3_config_s_fu_121->ap_ready(grp_dnn3_float_float_dense3_config_s_fu_121_ap_ready);
    grp_dnn3_float_float_dense3_config_s_fu_121->input_r_address0(grp_dnn3_float_float_dense3_config_s_fu_121_input_r_address0);
    grp_dnn3_float_float_dense3_config_s_fu_121->input_r_ce0(grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce0);
    grp_dnn3_float_float_dense3_config_s_fu_121->input_r_q0(O_sum_q0);
    grp_dnn3_float_float_dense3_config_s_fu_121->input_r_address1(grp_dnn3_float_float_dense3_config_s_fu_121_input_r_address1);
    grp_dnn3_float_float_dense3_config_s_fu_121->input_r_ce1(grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce1);
    grp_dnn3_float_float_dense3_config_s_fu_121->input_r_q1(O_sum_q1);
    grp_dnn3_float_float_dense3_config_s_fu_121->res_address0(grp_dnn3_float_float_dense3_config_s_fu_121_res_address0);
    grp_dnn3_float_float_dense3_config_s_fu_121->res_ce0(grp_dnn3_float_float_dense3_config_s_fu_121_res_ce0);
    grp_dnn3_float_float_dense3_config_s_fu_121->res_we0(grp_dnn3_float_float_dense3_config_s_fu_121_res_we0);
    grp_dnn3_float_float_dense3_config_s_fu_121->res_d0(grp_dnn3_float_float_dense3_config_s_fu_121_res_d0);
    grp_dnn3_float_float_dense3_config_s_fu_121->res_address1(grp_dnn3_float_float_dense3_config_s_fu_121_res_address1);
    grp_dnn3_float_float_dense3_config_s_fu_121->res_ce1(grp_dnn3_float_float_dense3_config_s_fu_121_res_ce1);
    grp_dnn3_float_float_dense3_config_s_fu_121->res_we1(grp_dnn3_float_float_dense3_config_s_fu_121_res_we1);
    grp_dnn3_float_float_dense3_config_s_fu_121->res_d1(grp_dnn3_float_float_dense3_config_s_fu_121_res_d1);
    jedi_fadd_32ns_32ns_32_4_full_dsp_1_U4578 = new jedi_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("jedi_fadd_32ns_32ns_32_4_full_dsp_1_U4578");
    jedi_fadd_32ns_32ns_32_4_full_dsp_1_U4578->clk(ap_clk);
    jedi_fadd_32ns_32ns_32_4_full_dsp_1_U4578->reset(ap_rst);
    jedi_fadd_32ns_32ns_32_4_full_dsp_1_U4578->din0(O_sum_load_reg_249);
    jedi_fadd_32ns_32ns_32_4_full_dsp_1_U4578->din1(O_load_reg_244);
    jedi_fadd_32ns_32ns_32_4_full_dsp_1_U4578->ce(ap_var_for_const0);
    jedi_fadd_32ns_32ns_32_4_full_dsp_1_U4578->dout(grp_fu_134_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_O_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln397_2_fu_200_p1 );

    SC_METHOD(thread_O_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_O_sum_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( O_sum_addr_1_reg_226 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_input_r_address0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( zext_ln391_fu_150_p1 );

    SC_METHOD(thread_O_sum_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_O_sum_ce1);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce1 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_O_sum_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_reg_254 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_O_sum_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln390_fu_138_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_add_ln395_fu_155_p2);
    sensitive << ( phi_mul_reg_98 );

    SC_METHOD(thread_add_ln397_fu_194_p2);
    sensitive << ( phi_mul_reg_98 );
    sensitive << ( zext_ln397_1_fu_190_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_ap_done );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_ap_done );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_cols_fu_184_p2);
    sensitive << ( cols_0_reg_110 );

    SC_METHOD(thread_grp_dnn3_float_float_dense3_config_s_fu_121_ap_start);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_ap_start_reg );

    SC_METHOD(thread_i_fu_144_p2);
    sensitive << ( i_0_reg_76 );

    SC_METHOD(thread_icmp_ln390_fu_138_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_76 );

    SC_METHOD(thread_icmp_ln395_fu_161_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( rows_0_reg_87 );

    SC_METHOD(thread_icmp_ln396_fu_178_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( cols_0_reg_110 );

    SC_METHOD(thread_res_address0);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_res_address0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_res_address1);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_res_address1 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_res_ce0);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_res_ce0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_res_ce1);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_res_ce1 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_res_d0);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_res_d0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_res_d1);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_res_d1 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_res_we0);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_res_we0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_res_we1);
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_res_we1 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_rows_fu_167_p2);
    sensitive << ( rows_0_reg_87 );

    SC_METHOD(thread_zext_ln391_fu_150_p1);
    sensitive << ( i_0_reg_76 );

    SC_METHOD(thread_zext_ln397_1_fu_190_p1);
    sensitive << ( cols_0_reg_110 );

    SC_METHOD(thread_zext_ln397_2_fu_200_p1);
    sensitive << ( add_ln397_fu_194_p2 );

    SC_METHOD(thread_zext_ln397_fu_173_p1);
    sensitive << ( rows_0_reg_87 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln395_fu_161_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln396_fu_178_p2 );
    sensitive << ( grp_dnn3_float_float_dense3_config_s_fu_121_ap_done );
    sensitive << ( icmp_ln390_fu_138_p2 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000001";
    grp_dnn3_float_float_dense3_config_s_fu_121_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "jedi_dnn3_float_float_dense3_config_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, O_address0, "(port)O_address0");
    sc_trace(mVcdFile, O_ce0, "(port)O_ce0");
    sc_trace(mVcdFile, O_q0, "(port)O_q0");
    sc_trace(mVcdFile, res_address0, "(port)res_address0");
    sc_trace(mVcdFile, res_ce0, "(port)res_ce0");
    sc_trace(mVcdFile, res_we0, "(port)res_we0");
    sc_trace(mVcdFile, res_d0, "(port)res_d0");
    sc_trace(mVcdFile, res_address1, "(port)res_address1");
    sc_trace(mVcdFile, res_ce1, "(port)res_ce1");
    sc_trace(mVcdFile, res_we1, "(port)res_we1");
    sc_trace(mVcdFile, res_d1, "(port)res_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_144_p2, "i_fu_144_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln395_fu_155_p2, "add_ln395_fu_155_p2");
    sc_trace(mVcdFile, add_ln395_reg_213, "add_ln395_reg_213");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, rows_fu_167_p2, "rows_fu_167_p2");
    sc_trace(mVcdFile, rows_reg_221, "rows_reg_221");
    sc_trace(mVcdFile, O_sum_addr_1_reg_226, "O_sum_addr_1_reg_226");
    sc_trace(mVcdFile, icmp_ln395_fu_161_p2, "icmp_ln395_fu_161_p2");
    sc_trace(mVcdFile, cols_fu_184_p2, "cols_fu_184_p2");
    sc_trace(mVcdFile, cols_reg_234, "cols_reg_234");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln396_fu_178_p2, "icmp_ln396_fu_178_p2");
    sc_trace(mVcdFile, O_load_reg_244, "O_load_reg_244");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, O_sum_q0, "O_sum_q0");
    sc_trace(mVcdFile, O_sum_load_reg_249, "O_sum_load_reg_249");
    sc_trace(mVcdFile, grp_fu_134_p2, "grp_fu_134_p2");
    sc_trace(mVcdFile, tmp_reg_254, "tmp_reg_254");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, O_sum_address0, "O_sum_address0");
    sc_trace(mVcdFile, O_sum_ce0, "O_sum_ce0");
    sc_trace(mVcdFile, O_sum_we0, "O_sum_we0");
    sc_trace(mVcdFile, O_sum_d0, "O_sum_d0");
    sc_trace(mVcdFile, O_sum_ce1, "O_sum_ce1");
    sc_trace(mVcdFile, O_sum_q1, "O_sum_q1");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_ap_start, "grp_dnn3_float_float_dense3_config_s_fu_121_ap_start");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_ap_done, "grp_dnn3_float_float_dense3_config_s_fu_121_ap_done");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_ap_idle, "grp_dnn3_float_float_dense3_config_s_fu_121_ap_idle");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_ap_ready, "grp_dnn3_float_float_dense3_config_s_fu_121_ap_ready");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_input_r_address0, "grp_dnn3_float_float_dense3_config_s_fu_121_input_r_address0");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce0, "grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce0");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_input_r_address1, "grp_dnn3_float_float_dense3_config_s_fu_121_input_r_address1");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce1, "grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce1");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_res_address0, "grp_dnn3_float_float_dense3_config_s_fu_121_res_address0");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_res_ce0, "grp_dnn3_float_float_dense3_config_s_fu_121_res_ce0");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_res_we0, "grp_dnn3_float_float_dense3_config_s_fu_121_res_we0");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_res_d0, "grp_dnn3_float_float_dense3_config_s_fu_121_res_d0");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_res_address1, "grp_dnn3_float_float_dense3_config_s_fu_121_res_address1");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_res_ce1, "grp_dnn3_float_float_dense3_config_s_fu_121_res_ce1");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_res_we1, "grp_dnn3_float_float_dense3_config_s_fu_121_res_we1");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_res_d1, "grp_dnn3_float_float_dense3_config_s_fu_121_res_d1");
    sc_trace(mVcdFile, i_0_reg_76, "i_0_reg_76");
    sc_trace(mVcdFile, icmp_ln390_fu_138_p2, "icmp_ln390_fu_138_p2");
    sc_trace(mVcdFile, rows_0_reg_87, "rows_0_reg_87");
    sc_trace(mVcdFile, phi_mul_reg_98, "phi_mul_reg_98");
    sc_trace(mVcdFile, cols_0_reg_110, "cols_0_reg_110");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_dnn3_float_float_dense3_config_s_fu_121_ap_start_reg, "grp_dnn3_float_float_dense3_config_s_fu_121_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, zext_ln391_fu_150_p1, "zext_ln391_fu_150_p1");
    sc_trace(mVcdFile, zext_ln397_fu_173_p1, "zext_ln397_fu_173_p1");
    sc_trace(mVcdFile, zext_ln397_2_fu_200_p1, "zext_ln397_2_fu_200_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, zext_ln397_1_fu_190_p1, "zext_ln397_1_fu_190_p1");
    sc_trace(mVcdFile, add_ln397_fu_194_p2, "add_ln397_fu_194_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

jedi_dnn3_float_float_dense3_config_s::~jedi_dnn3_float_float_dense3_config_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete O_sum_U;
    delete grp_dnn3_float_float_dense3_config_s_fu_121;
    delete jedi_fadd_32ns_32ns_32_4_full_dsp_1_U4578;
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln395_fu_161_p2.read(), ap_const_lv1_0))) {
        cols_0_reg_110 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        cols_0_reg_110 = cols_reg_234.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_dnn3_float_float_dense3_config_s_fu_121_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln395_fu_161_p2.read(), ap_const_lv1_1))) {
            grp_dnn3_float_float_dense3_config_s_fu_121_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dnn3_float_float_dense3_config_s_fu_121_ap_ready.read())) {
            grp_dnn3_float_float_dense3_config_s_fu_121_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln390_fu_138_p2.read()))) {
        i_0_reg_76 = i_fu_144_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_76 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln390_fu_138_p2.read(), ap_const_lv1_1))) {
        phi_mul_reg_98 = ap_const_lv11_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln396_fu_178_p2.read(), ap_const_lv1_1))) {
        phi_mul_reg_98 = add_ln395_reg_213.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln390_fu_138_p2.read(), ap_const_lv1_1))) {
        rows_0_reg_87 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln396_fu_178_p2.read(), ap_const_lv1_1))) {
        rows_0_reg_87 = rows_reg_221.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        O_load_reg_244 = O_q0.read();
        O_sum_load_reg_249 = O_sum_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln395_fu_161_p2.read(), ap_const_lv1_0))) {
        O_sum_addr_1_reg_226 =  (sc_lv<4>) (zext_ln397_fu_173_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln395_reg_213 = add_ln395_fu_155_p2.read();
        rows_reg_221 = rows_fu_167_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        cols_reg_234 = cols_fu_184_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp_reg_254 = grp_fu_134_p2.read();
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_O_address0() {
    O_address0 =  (sc_lv<11>) (zext_ln397_2_fu_200_p1.read());
}

void jedi_dnn3_float_float_dense3_config_s::thread_O_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        O_ce0 = ap_const_logic_1;
    } else {
        O_ce0 = ap_const_logic_0;
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_O_sum_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        O_sum_address0 = O_sum_addr_1_reg_226.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        O_sum_address0 =  (sc_lv<4>) (zext_ln391_fu_150_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        O_sum_address0 = grp_dnn3_float_float_dense3_config_s_fu_121_input_r_address0.read();
    } else {
        O_sum_address0 = "XXXX";
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_O_sum_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        O_sum_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        O_sum_ce0 = grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce0.read();
    } else {
        O_sum_ce0 = ap_const_logic_0;
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_O_sum_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        O_sum_ce1 = grp_dnn3_float_float_dense3_config_s_fu_121_input_r_ce1.read();
    } else {
        O_sum_ce1 = ap_const_logic_0;
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_O_sum_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        O_sum_d0 = tmp_reg_254.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        O_sum_d0 = ap_const_lv32_0;
    } else {
        O_sum_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_O_sum_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln390_fu_138_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        O_sum_we0 = ap_const_logic_1;
    } else {
        O_sum_we0 = ap_const_logic_0;
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_add_ln395_fu_155_p2() {
    add_ln395_fu_155_p2 = (!phi_mul_reg_98.read().is_01() || !ap_const_lv11_96.is_01())? sc_lv<11>(): (sc_biguint<11>(phi_mul_reg_98.read()) + sc_biguint<11>(ap_const_lv11_96));
}

void jedi_dnn3_float_float_dense3_config_s::thread_add_ln397_fu_194_p2() {
    add_ln397_fu_194_p2 = (!phi_mul_reg_98.read().is_01() || !zext_ln397_1_fu_190_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(phi_mul_reg_98.read()) + sc_biguint<11>(zext_ln397_1_fu_190_p1.read()));
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(grp_dnn3_float_float_dense3_config_s_fu_121_ap_done.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(grp_dnn3_float_float_dense3_config_s_fu_121_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void jedi_dnn3_float_float_dense3_config_s::thread_cols_fu_184_p2() {
    cols_fu_184_p2 = (!cols_0_reg_110.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(cols_0_reg_110.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void jedi_dnn3_float_float_dense3_config_s::thread_grp_dnn3_float_float_dense3_config_s_fu_121_ap_start() {
    grp_dnn3_float_float_dense3_config_s_fu_121_ap_start = grp_dnn3_float_float_dense3_config_s_fu_121_ap_start_reg.read();
}

void jedi_dnn3_float_float_dense3_config_s::thread_i_fu_144_p2() {
    i_fu_144_p2 = (!i_0_reg_76.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_76.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void jedi_dnn3_float_float_dense3_config_s::thread_icmp_ln390_fu_138_p2() {
    icmp_ln390_fu_138_p2 = (!i_0_reg_76.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_76.read() == ap_const_lv4_A);
}

void jedi_dnn3_float_float_dense3_config_s::thread_icmp_ln395_fu_161_p2() {
    icmp_ln395_fu_161_p2 = (!rows_0_reg_87.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(rows_0_reg_87.read() == ap_const_lv4_A);
}

void jedi_dnn3_float_float_dense3_config_s::thread_icmp_ln396_fu_178_p2() {
    icmp_ln396_fu_178_p2 = (!cols_0_reg_110.read().is_01() || !ap_const_lv8_96.is_01())? sc_lv<1>(): sc_lv<1>(cols_0_reg_110.read() == ap_const_lv8_96);
}

void jedi_dnn3_float_float_dense3_config_s::thread_res_address0() {
    res_address0 = grp_dnn3_float_float_dense3_config_s_fu_121_res_address0.read();
}

void jedi_dnn3_float_float_dense3_config_s::thread_res_address1() {
    res_address1 = grp_dnn3_float_float_dense3_config_s_fu_121_res_address1.read();
}

void jedi_dnn3_float_float_dense3_config_s::thread_res_ce0() {
    res_ce0 = grp_dnn3_float_float_dense3_config_s_fu_121_res_ce0.read();
}

void jedi_dnn3_float_float_dense3_config_s::thread_res_ce1() {
    res_ce1 = grp_dnn3_float_float_dense3_config_s_fu_121_res_ce1.read();
}

void jedi_dnn3_float_float_dense3_config_s::thread_res_d0() {
    res_d0 = grp_dnn3_float_float_dense3_config_s_fu_121_res_d0.read();
}

void jedi_dnn3_float_float_dense3_config_s::thread_res_d1() {
    res_d1 = grp_dnn3_float_float_dense3_config_s_fu_121_res_d1.read();
}

void jedi_dnn3_float_float_dense3_config_s::thread_res_we0() {
    res_we0 = grp_dnn3_float_float_dense3_config_s_fu_121_res_we0.read();
}

void jedi_dnn3_float_float_dense3_config_s::thread_res_we1() {
    res_we1 = grp_dnn3_float_float_dense3_config_s_fu_121_res_we1.read();
}

void jedi_dnn3_float_float_dense3_config_s::thread_rows_fu_167_p2() {
    rows_fu_167_p2 = (!rows_0_reg_87.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(rows_0_reg_87.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void jedi_dnn3_float_float_dense3_config_s::thread_zext_ln391_fu_150_p1() {
    zext_ln391_fu_150_p1 = esl_zext<64,4>(i_0_reg_76.read());
}

void jedi_dnn3_float_float_dense3_config_s::thread_zext_ln397_1_fu_190_p1() {
    zext_ln397_1_fu_190_p1 = esl_zext<11,8>(cols_0_reg_110.read());
}

void jedi_dnn3_float_float_dense3_config_s::thread_zext_ln397_2_fu_200_p1() {
    zext_ln397_2_fu_200_p1 = esl_zext<64,11>(add_ln397_fu_194_p2.read());
}

void jedi_dnn3_float_float_dense3_config_s::thread_zext_ln397_fu_173_p1() {
    zext_ln397_fu_173_p1 = esl_zext<64,4>(rows_0_reg_87.read());
}

void jedi_dnn3_float_float_dense3_config_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln390_fu_138_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln395_fu_161_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln396_fu_178_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(grp_dnn3_float_float_dense3_config_s_fu_121_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

