// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "jedi.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic jedi::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic jedi::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> jedi::ap_ST_fsm_state1 = "1";
const sc_lv<16> jedi::ap_ST_fsm_state2 = "10";
const sc_lv<16> jedi::ap_ST_fsm_state3 = "100";
const sc_lv<16> jedi::ap_ST_fsm_state4 = "1000";
const sc_lv<16> jedi::ap_ST_fsm_state5 = "10000";
const sc_lv<16> jedi::ap_ST_fsm_state6 = "100000";
const sc_lv<16> jedi::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> jedi::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> jedi::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> jedi::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> jedi::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> jedi::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> jedi::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> jedi::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> jedi::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> jedi::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> jedi::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> jedi::ap_const_lv32_6 = "110";
const sc_lv<32> jedi::ap_const_lv32_7 = "111";
const sc_lv<32> jedi::ap_const_lv32_C = "1100";
const sc_lv<32> jedi::ap_const_lv32_D = "1101";
const sc_lv<32> jedi::ap_const_lv32_E = "1110";
const sc_lv<32> jedi::ap_const_lv32_F = "1111";
const sc_lv<32> jedi::ap_const_lv32_1 = "1";
const sc_lv<32> jedi::ap_const_lv32_2 = "10";
const sc_lv<32> jedi::ap_const_lv32_3 = "11";
const sc_lv<32> jedi::ap_const_lv32_8 = "1000";
const sc_lv<32> jedi::ap_const_lv32_9 = "1001";
const sc_lv<32> jedi::ap_const_lv32_4 = "100";
const sc_lv<32> jedi::ap_const_lv32_5 = "101";
const sc_lv<32> jedi::ap_const_lv32_A = "1010";
const sc_lv<32> jedi::ap_const_lv32_B = "1011";
const bool jedi::ap_const_boolean_1 = true;

jedi::jedi(sc_module_name name) : sc_module(name), mVcdFile(0) {
    E_bar_U = new jedi_E_bar("E_bar_U");
    E_bar_U->clk(ap_clk);
    E_bar_U->reset(ap_rst);
    E_bar_U->address0(E_bar_address0);
    E_bar_U->ce0(E_bar_ce0);
    E_bar_U->we0(E_bar_we0);
    E_bar_U->d0(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_d0);
    E_bar_U->q0(E_bar_q0);
    B_top_U = new jedi_B_top("B_top_U");
    B_top_U->clk(ap_clk);
    B_top_U->reset(ap_rst);
    B_top_U->address0(B_top_address0);
    B_top_U->ce0(B_top_ce0);
    B_top_U->we0(B_top_we0);
    B_top_U->d0(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_d0);
    B_top_U->q0(B_top_q0);
    B_bot_U = new jedi_B_top("B_bot_U");
    B_bot_U->clk(ap_clk);
    B_bot_U->reset(ap_rst);
    B_bot_U->address0(B_bot_address0);
    B_bot_U->ce0(B_bot_ce0);
    B_bot_U->we0(B_bot_we0);
    B_bot_U->d0(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_d0);
    B_bot_U->q0(B_bot_q0);
    B_U = new jedi_B("B_U");
    B_U->clk(ap_clk);
    B_U->reset(ap_rst);
    B_U->address0(B_address0);
    B_U->ce0(B_ce0);
    B_U->we0(B_we0);
    B_U->d0(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_d0);
    B_U->q0(B_q0);
    E_U = new jedi_E("E_U");
    E_U->clk(ap_clk);
    E_U->reset(ap_rst);
    E_U->address0(E_address0);
    E_U->ce0(E_ce0);
    E_U->we0(E_we0);
    E_U->d0(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_d0);
    E_U->q0(E_q0);
    C_U = new jedi_C("C_U");
    C_U->clk(ap_clk);
    C_U->reset(ap_rst);
    C_U->address0(C_address0);
    C_U->ce0(C_ce0);
    C_U->we0(C_we0);
    C_U->d0(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_d0);
    C_U->q0(C_q0);
    O_U = new jedi_E_bar("O_U");
    O_U->clk(ap_clk);
    O_U->reset(ap_rst);
    O_U->address0(O_address0);
    O_U->ce0(O_ce0);
    O_U->we0(O_we0);
    O_U->d0(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_d0);
    O_U->q0(O_q0);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80 = new jedi_dnn1_float_float_dense1_config_s("grp_jedi_dnn1_float_float_dense1_config_s_fu_80");
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->ap_clk(ap_clk);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->ap_rst(ap_rst);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->ap_start(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->ap_done(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_done);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->ap_idle(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_idle);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->ap_ready(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_ready);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->B_address0(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_address0);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->B_ce0(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_ce0);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->B_q0(B_q0);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->E_address0(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_address0);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->E_ce0(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_ce0);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->E_we0(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_we0);
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80->E_d0(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_d0);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92 = new jedi_dnn2_float_float_dense2_config_s("grp_jedi_dnn2_float_float_dense2_config_s_fu_92");
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->ap_clk(ap_clk);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->ap_rst(ap_rst);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->ap_start(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->ap_done(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_done);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->ap_idle(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_idle);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->ap_ready(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_ready);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->C_address0(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_address0);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->C_ce0(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_ce0);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->C_q0(C_q0);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->O_address0(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_address0);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->O_ce0(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_ce0);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->O_we0(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_we0);
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92->O_d0(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_d0);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104 = new jedi_dnn3_float_float_dense3_config_s("grp_jedi_dnn3_float_float_dense3_config_s_fu_104");
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->ap_clk(ap_clk);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->ap_rst(ap_rst);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->ap_start(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->ap_done(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_done);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->ap_idle(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_idle);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->ap_ready(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_ready);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->O_address0(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_address0);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->O_ce0(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_ce0);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->O_q0(O_q0);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->res_address0(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address0);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->res_ce0(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce0);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->res_we0(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we0);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->res_d0(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d0);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->res_address1(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address1);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->res_ce1(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce1);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->res_we1(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we1);
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104->res_d1(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d1);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117 = new jedi_multiply_float_float_mult_1_struct_s("grp_jedi_multiply_float_float_mult_1_struct_s_fu_117");
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->ap_clk(ap_clk);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->ap_rst(ap_rst);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->ap_start(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->ap_done(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_done);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->ap_idle(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_idle);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->ap_ready(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_ready);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->data1_address0(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_address0);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->data1_ce0(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_ce0);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->data1_q0(I_q0);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->data2_address0(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_address0);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->data2_ce0(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_ce0);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->data2_q0(Rr_q0);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->res_address0(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_address0);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->res_ce0(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_ce0);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->res_we0(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_we0);
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117->res_d0(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_d0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127 = new jedi_multiply_float_float_mult_2_struct_s("grp_jedi_multiply_float_float_mult_2_struct_s_fu_127");
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->ap_clk(ap_clk);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->ap_rst(ap_rst);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->ap_start(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->ap_done(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_done);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->ap_idle(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_idle);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->ap_ready(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_ready);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->data1_address0(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_address0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->data1_ce0(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_ce0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->data1_q0(I_q0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->data2_address0(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_address0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->data2_ce0(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_ce0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->data2_q0(Rs_q0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->res_address0(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_address0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->res_ce0(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_ce0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->res_we0(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_we0);
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127->res_d0(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_d0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136 = new jedi_multiply_float_float_mult_3_struct_s("grp_jedi_multiply_float_float_mult_3_struct_s_fu_136");
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->ap_clk(ap_clk);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->ap_rst(ap_rst);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->ap_start(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->ap_done(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_done);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->ap_idle(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_idle);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->ap_ready(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_ready);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->data1_address0(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_address0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->data1_ce0(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_ce0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->data1_q0(E_q0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->data2_address0(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_address0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->data2_ce0(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_ce0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->data2_q0(Rr_T_q0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->res_address0(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_address0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->res_ce0(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_ce0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->res_we0(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_we0);
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136->res_d0(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_d0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144 = new jedi_concat_float_float_concat_1_struct_s("grp_jedi_concat_float_float_concat_1_struct_s_fu_144");
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->ap_clk(ap_clk);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->ap_rst(ap_rst);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->ap_start(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->ap_done(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_done);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->ap_idle(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_idle);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->ap_ready(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_ready);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->data1_address0(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_address0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->data1_ce0(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_ce0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->data1_q0(B_top_q0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->data2_address0(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_address0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->data2_ce0(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_ce0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->data2_q0(B_bot_q0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->res_address0(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_address0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->res_ce0(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_ce0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->res_we0(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_we0);
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144->res_d0(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_d0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151 = new jedi_concat_float_float_concat_2_struct_s("grp_jedi_concat_float_float_concat_2_struct_s_fu_151");
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->ap_clk(ap_clk);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->ap_rst(ap_rst);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->ap_start(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->ap_done(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_done);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->ap_idle(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_idle);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->ap_ready(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_ready);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->data1_address0(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_address0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->data1_ce0(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_ce0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->data1_q0(I_q0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->data2_address0(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_address0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->data2_ce0(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_ce0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->data2_q0(E_bar_q0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->res_address0(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_address0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->res_ce0(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_ce0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->res_we0(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_we0);
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151->res_d0(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_B_address0);
    sensitive << ( grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_address0 );
    sensitive << ( grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_B_bot_address0);
    sensitive << ( grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_address0 );
    sensitive << ( grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_B_bot_ce0);
    sensitive << ( grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_ce0 );
    sensitive << ( grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_ce0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_B_bot_we0);
    sensitive << ( grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_we0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_ce0 );
    sensitive << ( grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_ce0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_B_top_address0);
    sensitive << ( grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_address0 );
    sensitive << ( grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_B_top_ce0);
    sensitive << ( grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_ce0 );
    sensitive << ( grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_ce0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_B_top_we0);
    sensitive << ( grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_B_we0);
    sensitive << ( grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_we0 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_C_address0);
    sensitive << ( grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_address0 );
    sensitive << ( grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_address0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_ce0 );
    sensitive << ( grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_ce0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_C_we0);
    sensitive << ( grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_we0 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_E_address0);
    sensitive << ( grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_address0 );
    sensitive << ( grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_E_bar_address0);
    sensitive << ( grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_address0 );
    sensitive << ( grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_address0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_E_bar_ce0);
    sensitive << ( grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_ce0 );
    sensitive << ( grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_ce0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_E_bar_we0);
    sensitive << ( grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_we0 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_E_ce0);
    sensitive << ( grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_ce0 );
    sensitive << ( grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_ce0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_E_we0);
    sensitive << ( grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_we0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_I_address0);
    sensitive << ( grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_address0 );
    sensitive << ( grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_address0 );
    sensitive << ( grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_I_ce0);
    sensitive << ( grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_ce0 );
    sensitive << ( grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_ce0 );
    sensitive << ( grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_ce0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_O_address0);
    sensitive << ( grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_address0 );
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_address0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_O_ce0);
    sensitive << ( grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_ce0 );
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_ce0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_O_we0);
    sensitive << ( grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_we0 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_Rr_T_address0);
    sensitive << ( grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_address0 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_Rr_T_ce0);
    sensitive << ( grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_ce0 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_Rr_address0);
    sensitive << ( grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Rr_ce0);
    sensitive << ( grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Rs_address0);
    sensitive << ( grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_address0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Rs_ce0);
    sensitive << ( grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_ce0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_done );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_done );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start);
    sensitive << ( grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start_reg );

    SC_METHOD(thread_grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start);
    sensitive << ( grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start_reg );

    SC_METHOD(thread_grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start);
    sensitive << ( grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start_reg );

    SC_METHOD(thread_grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start);
    sensitive << ( grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start_reg );

    SC_METHOD(thread_grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start_reg );

    SC_METHOD(thread_grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start);
    sensitive << ( grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start_reg );

    SC_METHOD(thread_grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start);
    sensitive << ( grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start_reg );

    SC_METHOD(thread_grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start);
    sensitive << ( grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start_reg );

    SC_METHOD(thread_result_address0);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_result_address1);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address1 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_result_ce0);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_result_ce1);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce1 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_result_d0);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_result_d1);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d1 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_result_we0);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_result_we1);
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we1 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_done );
    sensitive << ( grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_done );
    sensitive << ( grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_done );
    sensitive << ( grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_done );
    sensitive << ( grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_done );
    sensitive << ( grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_done );
    sensitive << ( grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_done );
    sensitive << ( grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_done );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0000000000000001";
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start_reg = SC_LOGIC_0;
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start_reg = SC_LOGIC_0;
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start_reg = SC_LOGIC_0;
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start_reg = SC_LOGIC_0;
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start_reg = SC_LOGIC_0;
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start_reg = SC_LOGIC_0;
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start_reg = SC_LOGIC_0;
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "jedi_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, I_address0, "(port)I_address0");
    sc_trace(mVcdFile, I_ce0, "(port)I_ce0");
    sc_trace(mVcdFile, I_q0, "(port)I_q0");
    sc_trace(mVcdFile, Rr_address0, "(port)Rr_address0");
    sc_trace(mVcdFile, Rr_ce0, "(port)Rr_ce0");
    sc_trace(mVcdFile, Rr_q0, "(port)Rr_q0");
    sc_trace(mVcdFile, Rr_T_address0, "(port)Rr_T_address0");
    sc_trace(mVcdFile, Rr_T_ce0, "(port)Rr_T_ce0");
    sc_trace(mVcdFile, Rr_T_q0, "(port)Rr_T_q0");
    sc_trace(mVcdFile, Rs_address0, "(port)Rs_address0");
    sc_trace(mVcdFile, Rs_ce0, "(port)Rs_ce0");
    sc_trace(mVcdFile, Rs_q0, "(port)Rs_q0");
    sc_trace(mVcdFile, result_address0, "(port)result_address0");
    sc_trace(mVcdFile, result_ce0, "(port)result_ce0");
    sc_trace(mVcdFile, result_we0, "(port)result_we0");
    sc_trace(mVcdFile, result_d0, "(port)result_d0");
    sc_trace(mVcdFile, result_address1, "(port)result_address1");
    sc_trace(mVcdFile, result_ce1, "(port)result_ce1");
    sc_trace(mVcdFile, result_we1, "(port)result_we1");
    sc_trace(mVcdFile, result_d1, "(port)result_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, E_bar_address0, "E_bar_address0");
    sc_trace(mVcdFile, E_bar_ce0, "E_bar_ce0");
    sc_trace(mVcdFile, E_bar_we0, "E_bar_we0");
    sc_trace(mVcdFile, E_bar_q0, "E_bar_q0");
    sc_trace(mVcdFile, B_top_address0, "B_top_address0");
    sc_trace(mVcdFile, B_top_ce0, "B_top_ce0");
    sc_trace(mVcdFile, B_top_we0, "B_top_we0");
    sc_trace(mVcdFile, B_top_q0, "B_top_q0");
    sc_trace(mVcdFile, B_bot_address0, "B_bot_address0");
    sc_trace(mVcdFile, B_bot_ce0, "B_bot_ce0");
    sc_trace(mVcdFile, B_bot_we0, "B_bot_we0");
    sc_trace(mVcdFile, B_bot_q0, "B_bot_q0");
    sc_trace(mVcdFile, B_address0, "B_address0");
    sc_trace(mVcdFile, B_ce0, "B_ce0");
    sc_trace(mVcdFile, B_we0, "B_we0");
    sc_trace(mVcdFile, B_q0, "B_q0");
    sc_trace(mVcdFile, E_address0, "E_address0");
    sc_trace(mVcdFile, E_ce0, "E_ce0");
    sc_trace(mVcdFile, E_we0, "E_we0");
    sc_trace(mVcdFile, E_q0, "E_q0");
    sc_trace(mVcdFile, C_address0, "C_address0");
    sc_trace(mVcdFile, C_ce0, "C_ce0");
    sc_trace(mVcdFile, C_we0, "C_we0");
    sc_trace(mVcdFile, C_q0, "C_q0");
    sc_trace(mVcdFile, O_address0, "O_address0");
    sc_trace(mVcdFile, O_ce0, "O_ce0");
    sc_trace(mVcdFile, O_we0, "O_we0");
    sc_trace(mVcdFile, O_q0, "O_q0");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_done, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_done");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_idle, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_idle");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_ready, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_ready");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_address0, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_address0");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_ce0, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_ce0");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_address0, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_address0");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_ce0, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_ce0");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_we0, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_we0");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_d0, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_d0");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_done, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_done");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_idle, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_idle");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_ready, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_ready");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_address0, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_address0");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_ce0, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_ce0");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_address0, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_address0");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_ce0, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_ce0");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_we0, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_we0");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_d0, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_d0");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_done, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_done");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_idle, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_idle");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_ready, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_ready");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_address0, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_address0");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_ce0, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_ce0");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address0, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address0");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce0, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce0");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we0, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we0");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d0, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d0");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address1, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address1");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce1, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce1");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we1, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we1");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d1, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d1");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_done, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_done");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_idle, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_idle");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_ready, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_ready");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_address0, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_address0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_ce0, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_ce0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_address0, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_address0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_ce0, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_ce0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_address0, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_address0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_ce0, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_ce0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_we0, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_we0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_d0, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_d0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_done, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_done");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_idle, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_idle");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_ready, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_ready");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_address0, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_address0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_ce0, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_ce0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_address0, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_address0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_ce0, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_ce0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_address0, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_address0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_ce0, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_ce0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_we0, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_we0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_d0, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_d0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_done, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_done");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_idle, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_idle");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_ready, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_ready");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_address0, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_address0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_ce0, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_ce0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_address0, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_address0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_ce0, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_ce0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_address0, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_address0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_ce0, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_ce0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_we0, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_we0");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_d0, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_d0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_done, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_done");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_idle, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_idle");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_ready, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_ready");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_address0, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_address0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_ce0, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_ce0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_address0, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_address0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_ce0, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_ce0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_address0, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_address0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_ce0, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_ce0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_we0, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_we0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_d0, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_d0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_done, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_done");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_idle, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_idle");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_ready, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_ready");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_address0, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_address0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_ce0, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_ce0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_address0, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_address0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_ce0, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_ce0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_address0, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_address0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_ce0, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_ce0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_we0, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_we0");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_d0, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_d0");
    sc_trace(mVcdFile, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start_reg, "grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start_reg, "grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start_reg, "grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start_reg, "grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start_reg, "grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start_reg, "grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start_reg, "grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start_reg, "grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("jedi.hdltvin.dat");
    mHdltvoutHandle.open("jedi.hdltvout.dat");
}

jedi::~jedi() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete E_bar_U;
    delete B_top_U;
    delete B_bot_U;
    delete B_U;
    delete E_U;
    delete C_U;
    delete O_U;
    delete grp_jedi_dnn1_float_float_dense1_config_s_fu_80;
    delete grp_jedi_dnn2_float_float_dense2_config_s_fu_92;
    delete grp_jedi_dnn3_float_float_dense3_config_s_fu_104;
    delete grp_jedi_multiply_float_float_mult_1_struct_s_fu_117;
    delete grp_jedi_multiply_float_float_mult_2_struct_s_fu_127;
    delete grp_jedi_multiply_float_float_mult_3_struct_s_fu_136;
    delete grp_jedi_concat_float_float_concat_1_struct_s_fu_144;
    delete grp_jedi_concat_float_float_concat_2_struct_s_fu_151;
}

void jedi::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
            grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_ready.read())) {
            grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_ready.read())) {
            grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
            grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_ready.read())) {
            grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
            grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_ready.read())) {
            grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
            grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_ready.read())) {
            grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_ready.read())) {
            grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_ready.read())) {
            grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_ready.read())) {
            grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start_reg = ap_const_logic_0;
        }
    }
}

void jedi::thread_B_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        B_address0 = grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        B_address0 = grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_address0.read();
    } else {
        B_address0 = "XXXXXXXXXXXXXXXXXXXX";
    }
}

void jedi::thread_B_bot_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        B_bot_address0 = grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        B_bot_address0 = grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_address0.read();
    } else {
        B_bot_address0 =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
    }
}

void jedi::thread_B_bot_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        B_bot_ce0 = grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data2_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        B_bot_ce0 = grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_ce0.read();
    } else {
        B_bot_ce0 = ap_const_logic_0;
    }
}

void jedi::thread_B_bot_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        B_bot_we0 = grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_res_we0.read();
    } else {
        B_bot_we0 = ap_const_logic_0;
    }
}

void jedi::thread_B_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        B_ce0 = grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        B_ce0 = grp_jedi_dnn1_float_float_dense1_config_s_fu_80_B_ce0.read();
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void jedi::thread_B_top_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        B_top_address0 = grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        B_top_address0 = grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_address0.read();
    } else {
        B_top_address0 =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
    }
}

void jedi::thread_B_top_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        B_top_ce0 = grp_jedi_concat_float_float_concat_1_struct_s_fu_144_data1_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        B_top_ce0 = grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_ce0.read();
    } else {
        B_top_ce0 = ap_const_logic_0;
    }
}

void jedi::thread_B_top_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        B_top_we0 = grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_res_we0.read();
    } else {
        B_top_we0 = ap_const_logic_0;
    }
}

void jedi::thread_B_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        B_we0 = grp_jedi_concat_float_float_concat_1_struct_s_fu_144_res_we0.read();
    } else {
        B_we0 = ap_const_logic_0;
    }
}

void jedi::thread_C_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        C_address0 = grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        C_address0 = grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_address0.read();
    } else {
        C_address0 =  (sc_lv<12>) ("XXXXXXXXXXXX");
    }
}

void jedi::thread_C_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        C_ce0 = grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        C_ce0 = grp_jedi_dnn2_float_float_dense2_config_s_fu_92_C_ce0.read();
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void jedi::thread_C_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        C_we0 = grp_jedi_concat_float_float_concat_2_struct_s_fu_151_res_we0.read();
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void jedi::thread_E_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        E_address0 = grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        E_address0 = grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_address0.read();
    } else {
        E_address0 =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
    }
}

void jedi::thread_E_bar_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        E_bar_address0 = grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        E_bar_address0 = grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_address0.read();
    } else {
        E_bar_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void jedi::thread_E_bar_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        E_bar_ce0 = grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data2_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        E_bar_ce0 = grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_ce0.read();
    } else {
        E_bar_ce0 = ap_const_logic_0;
    }
}

void jedi::thread_E_bar_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        E_bar_we0 = grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_res_we0.read();
    } else {
        E_bar_we0 = ap_const_logic_0;
    }
}

void jedi::thread_E_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        E_ce0 = grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data1_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        E_ce0 = grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_ce0.read();
    } else {
        E_ce0 = ap_const_logic_0;
    }
}

void jedi::thread_E_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        E_we0 = grp_jedi_dnn1_float_float_dense1_config_s_fu_80_E_we0.read();
    } else {
        E_we0 = ap_const_logic_0;
    }
}

void jedi::thread_I_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        I_address0 = grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        I_address0 = grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        I_address0 = grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_address0.read();
    } else {
        I_address0 =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
    }
}

void jedi::thread_I_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        I_ce0 = grp_jedi_concat_float_float_concat_2_struct_s_fu_151_data1_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        I_ce0 = grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data1_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        I_ce0 = grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data1_ce0.read();
    } else {
        I_ce0 = ap_const_logic_0;
    }
}

void jedi::thread_O_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        O_address0 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        O_address0 = grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_address0.read();
    } else {
        O_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void jedi::thread_O_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        O_ce0 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_O_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        O_ce0 = grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_ce0.read();
    } else {
        O_ce0 = ap_const_logic_0;
    }
}

void jedi::thread_O_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        O_we0 = grp_jedi_dnn2_float_float_dense2_config_s_fu_92_O_we0.read();
    } else {
        O_we0 = ap_const_logic_0;
    }
}

void jedi::thread_Rr_T_address0() {
    Rr_T_address0 = grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_address0.read();
}

void jedi::thread_Rr_T_ce0() {
    Rr_T_ce0 = grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_data2_ce0.read();
}

void jedi::thread_Rr_address0() {
    Rr_address0 = grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_address0.read();
}

void jedi::thread_Rr_ce0() {
    Rr_ce0 = grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_data2_ce0.read();
}

void jedi::thread_Rs_address0() {
    Rs_address0 = grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_address0.read();
}

void jedi::thread_Rs_ce0() {
    Rs_ce0 = grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_data2_ce0.read();
}

void jedi::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void jedi::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void jedi::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void jedi::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void jedi::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void jedi::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void jedi::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void jedi::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void jedi::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void jedi::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void jedi::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void jedi::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void jedi::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void jedi::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void jedi::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void jedi::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void jedi::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_done.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void jedi::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void jedi::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void jedi::thread_grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start() {
    grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start = grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_start_reg.read();
}

void jedi::thread_grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start() {
    grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start = grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_start_reg.read();
}

void jedi::thread_grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start() {
    grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start = grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_start_reg.read();
}

void jedi::thread_grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start() {
    grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start = grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_start_reg.read();
}

void jedi::thread_grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start() {
    grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_start_reg.read();
}

void jedi::thread_grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start() {
    grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start = grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_start_reg.read();
}

void jedi::thread_grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start() {
    grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start = grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_start_reg.read();
}

void jedi::thread_grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start() {
    grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start = grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_start_reg.read();
}

void jedi::thread_result_address0() {
    result_address0 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address0.read();
}

void jedi::thread_result_address1() {
    result_address1 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_address1.read();
}

void jedi::thread_result_ce0() {
    result_ce0 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce0.read();
}

void jedi::thread_result_ce1() {
    result_ce1 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_ce1.read();
}

void jedi::thread_result_d0() {
    result_d0 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d0.read();
}

void jedi::thread_result_d1() {
    result_d1 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_d1.read();
}

void jedi::thread_result_we0() {
    result_we0 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we0.read();
}

void jedi::thread_result_we1() {
    result_we1 = grp_jedi_dnn3_float_float_dense3_config_s_fu_104_res_we1.read();
}

void jedi::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_jedi_multiply_float_float_mult_1_struct_s_fu_117_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_jedi_multiply_float_float_mult_2_struct_s_fu_127_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_jedi_concat_float_float_concat_1_struct_s_fu_144_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(grp_jedi_dnn1_float_float_dense1_config_s_fu_80_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(grp_jedi_multiply_float_float_mult_3_struct_s_fu_136_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(grp_jedi_concat_float_float_concat_2_struct_s_fu_151_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(grp_jedi_dnn2_float_float_dense2_config_s_fu_92_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(grp_jedi_dnn3_float_float_dense3_config_s_fu_104_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

void jedi::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"I_address0\" :  \"" << I_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"I_ce0\" :  \"" << I_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"I_q0\" :  \"" << I_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Rr_address0\" :  \"" << Rr_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Rr_ce0\" :  \"" << Rr_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Rr_q0\" :  \"" << Rr_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Rr_T_address0\" :  \"" << Rr_T_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Rr_T_ce0\" :  \"" << Rr_T_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Rr_T_q0\" :  \"" << Rr_T_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Rs_address0\" :  \"" << Rs_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Rs_ce0\" :  \"" << Rs_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Rs_q0\" :  \"" << Rs_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_address0\" :  \"" << result_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_ce0\" :  \"" << result_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_we0\" :  \"" << result_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_d0\" :  \"" << result_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_address1\" :  \"" << result_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_ce1\" :  \"" << result_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_we1\" :  \"" << result_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_d1\" :  \"" << result_d1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

