// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _jedi_concat_float_float_concat_1_struct_s_HH_
#define _jedi_concat_float_float_concat_1_struct_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "jedi_mul_mul_5ns_16ns_20_1_1.h"

namespace ap_rtl {

struct jedi_concat_float_float_concat_1_struct_s : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<19> > data1_address0;
    sc_out< sc_logic > data1_ce0;
    sc_in< sc_lv<32> > data1_q0;
    sc_out< sc_lv<19> > data2_address0;
    sc_out< sc_logic > data2_ce0;
    sc_in< sc_lv<32> > data2_q0;
    sc_out< sc_lv<20> > res_address0;
    sc_out< sc_logic > res_ce0;
    sc_out< sc_logic > res_we0;
    sc_out< sc_lv<32> > res_d0;


    // Module declarations
    jedi_concat_float_float_concat_1_struct_s(sc_module_name name);
    SC_HAS_PROCESS(jedi_concat_float_float_concat_1_struct_s);

    ~jedi_concat_float_float_concat_1_struct_s();

    sc_trace_file* mVcdFile;

    jedi_mul_mul_5ns_16ns_20_1_1<1,1,5,16,20>* jedi_mul_mul_5ns_16ns_20_1_1_U13;
    sc_signal< sc_lv<9> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<19> > add_ln78_fu_149_p2;
    sc_signal< sc_lv<19> > add_ln78_reg_268;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<5> > i_fu_161_p2;
    sc_signal< sc_lv<5> > i_reg_276;
    sc_signal< sc_lv<15> > j_fu_173_p2;
    sc_signal< sc_lv<15> > j_reg_284;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > zext_ln80_2_fu_189_p1;
    sc_signal< sc_lv<64> > zext_ln80_2_reg_289;
    sc_signal< sc_lv<1> > icmp_ln79_fu_167_p2;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<19> > add_ln87_fu_194_p2;
    sc_signal< sc_lv<19> > add_ln87_reg_309;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<5> > i_2_fu_206_p2;
    sc_signal< sc_lv<5> > i_2_reg_317;
    sc_signal< sc_lv<20> > mul_ln89_fu_262_p2;
    sc_signal< sc_lv<20> > mul_ln89_reg_322;
    sc_signal< sc_lv<1> > icmp_ln87_fu_200_p2;
    sc_signal< sc_lv<15> > j_2_fu_228_p2;
    sc_signal< sc_lv<15> > j_2_reg_330;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > icmp_ln88_fu_222_p2;
    sc_signal< sc_lv<20> > add_ln89_2_fu_253_p2;
    sc_signal< sc_lv<20> > add_ln89_2_reg_340;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<5> > i_0_reg_81;
    sc_signal< sc_lv<19> > phi_mul_reg_92;
    sc_signal< sc_lv<15> > j_0_reg_104;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > icmp_ln78_fu_155_p2;
    sc_signal< sc_lv<5> > i1_0_reg_115;
    sc_signal< sc_lv<19> > phi_mul1_reg_126;
    sc_signal< sc_lv<15> > j2_0_reg_138;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<64> > zext_ln89_6_fu_248_p1;
    sc_signal< sc_lv<64> > zext_ln89_7_fu_258_p1;
    sc_signal< sc_lv<19> > zext_ln80_fu_179_p1;
    sc_signal< sc_lv<19> > add_ln80_fu_183_p2;
    sc_signal< sc_lv<5> > xor_ln89_fu_212_p2;
    sc_signal< sc_lv<19> > zext_ln89_5_fu_238_p1;
    sc_signal< sc_lv<19> > add_ln89_fu_242_p2;
    sc_signal< sc_lv<20> > zext_ln89_4_fu_234_p1;
    sc_signal< sc_lv<5> > mul_ln89_fu_262_p0;
    sc_signal< sc_lv<16> > mul_ln89_fu_262_p1;
    sc_signal< sc_lv<9> > ap_NS_fsm;
    sc_signal< sc_lv<20> > mul_ln89_fu_262_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<9> ap_ST_fsm_state1;
    static const sc_lv<9> ap_ST_fsm_state2;
    static const sc_lv<9> ap_ST_fsm_state3;
    static const sc_lv<9> ap_ST_fsm_state4;
    static const sc_lv<9> ap_ST_fsm_state5;
    static const sc_lv<9> ap_ST_fsm_state6;
    static const sc_lv<9> ap_ST_fsm_state7;
    static const sc_lv<9> ap_ST_fsm_state8;
    static const sc_lv<9> ap_ST_fsm_state9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<19> ap_const_lv19_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<15> ap_const_lv15_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<19> ap_const_lv19_574E;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<15> ap_const_lv15_574E;
    static const sc_lv<15> ap_const_lv15_1;
    static const sc_lv<20> ap_const_lv20_574E;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln78_fu_149_p2();
    void thread_add_ln80_fu_183_p2();
    void thread_add_ln87_fu_194_p2();
    void thread_add_ln89_2_fu_253_p2();
    void thread_add_ln89_fu_242_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_data1_address0();
    void thread_data1_ce0();
    void thread_data2_address0();
    void thread_data2_ce0();
    void thread_i_2_fu_206_p2();
    void thread_i_fu_161_p2();
    void thread_icmp_ln78_fu_155_p2();
    void thread_icmp_ln79_fu_167_p2();
    void thread_icmp_ln87_fu_200_p2();
    void thread_icmp_ln88_fu_222_p2();
    void thread_j_2_fu_228_p2();
    void thread_j_fu_173_p2();
    void thread_mul_ln89_fu_262_p0();
    void thread_mul_ln89_fu_262_p00();
    void thread_mul_ln89_fu_262_p1();
    void thread_res_address0();
    void thread_res_ce0();
    void thread_res_d0();
    void thread_res_we0();
    void thread_xor_ln89_fu_212_p2();
    void thread_zext_ln80_2_fu_189_p1();
    void thread_zext_ln80_fu_179_p1();
    void thread_zext_ln89_4_fu_234_p1();
    void thread_zext_ln89_5_fu_238_p1();
    void thread_zext_ln89_6_fu_248_p1();
    void thread_zext_ln89_7_fu_258_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
