Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    fc2:
      Precision:
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
    fc2_relu:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
    fc3:
      Precision:
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
    fc3_relu:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
    output:
      Precision:
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
    output_softmax:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
    rnn1:
      Precision: ap_fixed<16,6>
    rnn1_input:
      Precision:
        result: ap_fixed<16,6>
    rnn1_tanh:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
KerasModel: !keras_model 'rnn_model/hls4ml_prj_2/keras_model.h5'
OutputDir: rnn_model/hls4ml_prj_2
ProjectName: myproject
Stamp: 9cDC8F6d
XilinxPart: xcu250-figd2104-2L-e
